# Fonts
cask "font-jetbrains-mono-nerd-font"

# Shell Tools
brew "telnet"
brew "bzip2"
brew "git"

# Essentials
cask "ghostty"
brew "starship"
brew "mise"
brew "tmux"
brew "stow"

# Alternatives to popular CLI Tools
brew "bat"  # A cat clone with wings.
brew "eza"  # A simple, fast, and modern ls replacement.
brew "tldr" # Simplified man pages.

# Thrid-party CLI Tools
brew "gh"   # GitHub CLI.
brew "exercism" # Exercism CLI.

# Everything Containers
cask "orbstack" # A simple app to manage Docker containers.
brew "kubectx"  # Switch faster between Kubernetes contexts.
brew "minikube" # Run Kubernetes locally.

# MacOS Apps
cask "bluesnooze"       # A simple app to toggle Bluetooth on/off on lid close.
cask "hiddenbar"        # A simple app to hide the menu bar icons.
cask "monitorcontrol"   # A simple app to control external monitor brightness.

# Development Tools
cask "visual-studio-code"

# Browsers
cask "brave-browser"   # Privacy focused browser

# Apps
cask "notion"
cask "discord"
cask "whatsapp"
cask "pcsx2"
cask "ente-auth"
