# Fonts
cask "font-jetbrains-mono-nerd-font"

# Shell Tools
brew "telnet"
brew "bzip2"
brew "git"
brew "tree"

# Essentials
cask "ghostty"
brew "starship"
brew "mise"
brew "tmux"
brew "stow"

# Alternatives to popular CLI Tools
brew "bat"  # A cat clone with wings.
brew "eza"  # A simple, fast, and modern ls replacement.
brew "tldr" # Simplified man pages.

# Third-party CLI Tools
brew "gh"       # GitHub CLI.
brew "exercism" # Exercism CLI.
brew "awscli"   # AWS CLI v2, the unified tool to manage AWS services.

# Everything Containers
cask "orbstack" # A simple app to manage Docker containers.

# Kubernetes
brew "kubectx"  # Switch faster between Kubernetes contexts.
brew "kind"     # Run Kubernetes locally.

# AWS 


# AI
cask "claude-code"

# IaC 
brew "tenv"

# MacOS Apps
cask "bluesnooze"       # A simple app to toggle Bluetooth on/off on lid close.
cask "hiddenbar"        # A simple app to hide the menu bar icons.
cask "betterdisplay"
cask "rectangle"
cask "logi-options+"
cask "maccy"
cask "battery"
cask "caffeine"

# Development Tools
cask "visual-studio-code"

# Databases
cask "dbgate"

# Browsers
cask "brave-browser"   # Privacy focused browser

# Communication
cask "slack"
cask "discord"
cask "whatsapp"

# Productivity
cask "notion"
cask "obsidian"

# Emulators
cask "pcsx2"
