# Set the prefix key to `
unbind-key C-b
bind-key ` send-prefix
set -g prefix `

# Set the default terminal to support 256 colors
set -g default-terminal "xterm-256color"

# Set the base index for windows and panes to 1
set -g base-index 1
set -g pane-base-index 1
# Automatically renumber windows when one is closed
set -g renumber-windows on

# Enable mouse support
set -g mouse on

# Key bindings for splitting panes
bind | split-window -h
bind - split-window -v
